export default {
    USER_LOGIN: "USER_LOGIN_INIT",
    USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
    USER_LOGIN_FAILED: "USER_LOGIN_FAILED",
    USER_REGISTER: "USER_REGISTER_INIT",
    USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
    USER_REGISTER_FAILED: "USER_REGISTER_FAILED"
};