export default {
    SEND_MESSAGE_INIT: "SEND_MESSAGE_INIT",
    SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
    SEND_MESSAGE_FAILED: "SEND_MESSAGE_FAILED",
    SAVE_MESSAGE_INIT: "SAVE_MESSAGE_INIT",
    SAVE_MESSAGE_SUCCESS: "SAVE_MESSAGE_SUCCESS",
    SAVE_MESSAGE_FAILED: "SAVE_MESSAGE_FAILED",
    NEW_CHAT_INIT: "NEW_CHAT_INIT",
    NEW_CHAT_SUCCESS: "NEW_CHAT_SUCCESS",
    NEW_CHAT_FAILED: "NEW_CHAT_FAILED",
    FINISH_CHAT_INIT: "FINISH_CHAT_INIT",
    FINISH_CHAT_SUCCESS: "FINISH_CHAT_SUCCESS",
    FINISH_CHAT_FAILED: "FINISH_CHAT_FAILED",
    ACTIVATE_RECENT_CHAT_INIT: "ACTIVATE_RECENT_CHAT_INIT",
    ACTIVATE_RECENT_CHAT_SUCCESS: "ACTIVATE_RECENT_CHAT_SUCCESS",
    ACTIVATE_RECENT_CHAT_FAILED: "ACTIVATE_RECENT_CHAT_FAILED"
};